name: CI

on:
  push:
    branches:
      - 'phase*'
      - main
  pull_request:
    branches:
      - 'phase*'
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build-essential
        run: sudo apt update && sudo apt install -y build-essential pkg-config uuid-dev sqlite3 libsqlite3-dev libncurses5-dev libncursesw5-dev 

      - name: build
        run: make all